export centord
export chartypeid
export classmult
export classtypes
export degree
export eesubs
export genchartab
export generic_cyclotomic_ring
export greenfuntab
export info
export kempner
export kempner_with_data
export lincomb
export nesum
export norm
export nrchars
export nrclasses
export nrirrchars
export nrparams
export omega
export order
export ortho2norm
export ortho2scalar
export param
export params
export printclassparam
export printinfochar
export printinfoclass
export printval
export scalar_product
export setcongruence
export specclassparam!
export specialize
export tensor_product
